name: Build and Deploy
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    # 虚拟机环境 ubuntu-latest，ubuntu-18.04或ubuntu-16.04
    # windows-latest，windows-2019或windows-2016
    # macOS-latest或macOS-10.14
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: 设置Node环境
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0
      - name: 下载依赖
        run: npm install

      - name: 编译
        run: npx tsc  
        env:
            CI: true
      - name: Prepare artifacts
        run: |
          mkdir output
          cp -R dist/* output/  # 假设打包产物在 dist 目录下
      
      - name: 移动dist到新分支
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./output  # 设置要推送的目录
          publish_branch: xm-rn-deploy  # 指定目标分支（可根据需要修改）