name: Build and Deploy
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    # 虚拟机环境 ubuntu-latest，ubuntu-18.04或ubuntu-16.04
    # windows-latest，windows-2019或windows-2016
    # macOS-latest或macOS-10.14
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: 设置Node环境
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0
      - name: 下载依赖
        run: npm install

      - name: 编译
        run: npx tsc  
        env:
            CI: true
      - name: Deploy to xm-rn-deploy
        run: |
          cd dist  
          git init
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b xm-rn-deploy  # 创建或切换到新分支
          git add .
          git commit -m "Deploy build artifacts"
          git push origin HEAD:xm-rn-deploy --force  # 强制推送到新分支
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 